Better `paint` errors. (#1846)
Since we have support for ACC loading, the errors thrown by `paint` are no longer
sufficiently informative. Even before that it was already hard to correlate source 
and locus of painting errors.

Example
```
$> python3 main.C51A.py
Traceback (most recent call last):
  File "main.C51A.py", line 33, in <module>
    cell = A.cable_cell(morph, labels, decor)
RuntimeError: cable_cell: cable (cable 6 0 1) overpaints
```
This adds more details to the error message
```
$> python3 main.C51A.py
Traceback (most recent call last):
  File "main.C51A.py", line 33, in <module>
    cell = A.cable_cell(morph, labels, decor)
RuntimeError: cable_cell: Setting property 'ion-reversal-potential' on region '(region "soma_group")' overpaints at '(cable 6 0 1)'
```